//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyThuVien
{
    using System;
    using System.Collections.Generic;
    
    public partial class PhieuViPham
    {
        public string MaPhieuViPham { get; set; }
        public string MaThuThu { get; set; }
        public string MaPhieuMuon { get; set; }
        public string MaViPham { get; set; }
        public int TienPhat { get; set; }
    
        public virtual NoiQuyViPham NoiQuyViPham { get; set; }
        public virtual PhieuMuonSach PhieuMuonSach { get; set; }
        public virtual ThuThu ThuThu { get; set; }
    }
}
