//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyThuVien
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sach
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Sach()
        {
            this.BanSaos = new HashSet<BanSao>();
            this.TacGias = new HashSet<TacGia>();
            this.TheLoais = new HashSet<TheLoai>();
        }
    
        public string MaSach { get; set; }
        public string MaTacGia { get; set; }
        public string MaKeSach { get; set; }
        public int GiaTien { get; set; }
        public string TomTatNoiDung { get; set; }
        public int NamXuatBan { get; set; }
        public string NgonNgu { get; set; }
        public string NhaXuatBan { get; set; }
        public string TenSach { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BanSao> BanSaos { get; set; }
        public virtual KeSach KeSach { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TacGia> TacGias { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TheLoai> TheLoais { get; set; }
    }
}
